server:
  port: 8080

spring:
  datasource:
    username: root
    password: v3J6YHPK
    url: jdbc:mysql://47.103.203.62:3306/JingDong
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/jd/mapper/*Mapper.xml
  type-aliases-package: com.jd.entity

#showSql
logging:
  level:
    com:
      jd:
        mapper: debug